Css index
12a1070/Your-Recipes pull request #15
Opened 2024-04-11 14:16 UTC by 12a1070

**index画面のCSS作成**

- 検索欄
- レシピ画像
- レシピのリンク
- 作成者と投稿日
- 編集するリンク

以上のCSSを作成

2024-04-11 22:59 UTC, yuki-b4 requested changes

2024-04-11 22:59 UTC, yuki-b4 commented on app/assets/stylesheets/application.css
> +  gap: 50px 50px;
左右上下全て同じ値なら、`gap: 50px`で

2024-04-11 22:59 UTC, yuki-b4 commented on app/assets/stylesheets/application.css
> +  margin-top: 2rem;
Q. ここだけ単位をrem使っているのは何か理由ありますか？

2024-04-11 22:59 UTC, yuki-b4 commented on app/assets/stylesheets/application.css
> +
不要であれば削除

2024-04-11 22:59 UTC, yuki-b4 commented on app/assets/stylesheets/index.css
> +
不要な空白削除

2024-04-11 22:59 UTC, yuki-b4 commented on app/assets/stylesheets/index.css
> +}
これ必要ですか？

2024-04-11 22:59 UTC, yuki-b4 commented on app/assets/stylesheets/index.css
> +
不要な空白削除

2024-04-11 22:59 UTC, yuki-b4 commented on app/assets/stylesheets/index.css
> +
不要な空白を削除

2024-04-11 22:59 UTC, yuki-b4 commented on app/assets/stylesheets/index.css
> +  margin-right: 21px;
これは、`.edit`の親要素にpaddingを指定する形で書き直しましょう！
余白は外側から内側のイメージです（これだと内側から外側になってしまっている）

2024-04-11 22:59 UTC, yuki-b4 commented on app/assets/stylesheets/index.css
> +  margin-right: 21px;
42行目の`.photo`も同様に直しましょう。

2024-04-11 22:59 UTC, yuki-b4 commented on app/views/recipes/index.html.erb
> +              <div class="edit"><%= link_to "編集する", edit_recipe_path(recipe) ,class:"edit"%></div>
`class`前のカンマの位置がおかしい
`edit_recipe_path(recipe) ,class:"edit"`

2024-04-12 11:21 UTC, 12a1070 reviewed
**index画面　編集、削除**

- 各要素のcss
- 余分な空欄

2024-04-12 13:10 UTC, yuki-b4 requested changes
もういっちょ！

2024-04-12 13:10 UTC, yuki-b4 commented on app/assets/stylesheets/application.css
> +
不要な空白あります！

2024-04-12 13:10 UTC, yuki-b4 commented on app/assets/stylesheets/index.css
> +  padding-right: 21px;
違いますね！
親要素（`list_box`ですかね）にpadding付与です！

2024-04-13 02:25 UTC, 12a1070 commented on app/assets/stylesheets/index.css
> +  padding-right: 21px;
<img width="382" alt="スクリーンショット 2024-04-13 11 23 27" src="https://github.com/12a1070/Your-Recipes/assets/86764150/e60bf1cb-7df4-4e89-8de8-791c8a5bc346">

list_box.にpadding-bottom: 75px;

2024-04-13 02:55 UTC, yuki-b4 commented on app/assets/stylesheets/index.css
> +  padding-right: 21px;
このpadding消して実現できるはずなので、考えてやってみてください！

2024-04-13 12:39 UTC, merged