Recipe image
12a1070/Your-Recipes pull request #4
Opened 2023-10-30 13:40 UTC by 12a1070

画像投稿機能追加

2023-10-31 13:46 UTC, 12a1070 commented
現状
・レシピ投稿機能でエラー
・レシピ投稿のためにナビゲーションを作るべきだったと思ったがどう作ればいいか不明

2023-11-09 16:18 UTC, 12a1070 commented
作成日時表示
画像表示
indexページのHTML完了

2023-11-10 00:36 UTC, yuki-b4 requested changes

2023-11-10 00:36 UTC, yuki-b4 commented on app/controllers/application_controller.rb
> +
余白が一行多いので削除で

2023-11-10 00:36 UTC, yuki-b4 commented on app/controllers/recipes_controller.rb
>        end
インデントを35行目のrecipeの列と揃えましょう

2023-11-10 00:36 UTC, yuki-b4 commented on app/controllers/recipes_controller.rb
> +    @recipe.user_id = current_user.id
recipe_paramsでuser_idをマージしているので不要かと思いますがどうでしょう？

2023-11-10 00:36 UTC, yuki-b4 commented on public/uploads/recipe/photo/1/スクリーンショット_2021-11-03_0.40.31.png
recipe/photo 配下の画像は全て削除でお願いします、必要なら理由を教えてください。

2023-11-10 11:26 UTC, 12a1070 reviewed
11/10 20:24　修正しました

2023-11-10 13:01 UTC, yuki-b4 commented on app/controllers/recipes_controller.rb
> +    @recipe.user_id = current_user.id
12行目だけです！よくみてくださいね！

2023-11-10 13:05 UTC, yuki-b4 commented on public/uploads/recipe/photo/1/スクリーンショット_2021-11-03_0.40.31.png
tmpも消せれば消してください

2023-11-10 16:23 UTC, 12a1070 reviewed
recipes_controller修正

2023-11-10 22:40 UTC, yuki-b4 requested changes
@12a1070 
お願いします

2023-11-10 22:40 UTC, yuki-b4 commented on app/controllers/recipes_controller.rb
> +    @recipe.user_id = current_user.id
12行目の`@recipe.user_id = current_user.id`だけ削除してください！
もしそれでsaveできなければ、この指摘は無視で大丈夫です

2023-11-11 03:48 UTC, 12a1070 commented
recipeコントローラーのクリエイトの@recipe.user_id = current_user.idを削除してもパスしました。

2023-11-11 06:59 UTC, yuki-b4 approved these changes

2023-11-12 12:28 UTC, merged