Edit
12a1070/Your-Recipes pull request #6
Opened 2023-11-23 23:48 UTC by 12a1070

編集機能作成
-recipeのeditページ実装
 -一覧ページに編集ページのリンクを貼り付け
-  recipe_userとcurrent_userが一致してない時に編集リンクを表示させない。

2023-11-24 14:10 UTC, yuki-b4 requested changes
お願いします！

2023-11-24 14:10 UTC, yuki-b4 commented on app/controllers/recipes_controller.rb
> +  # before_action :correct_user, only: [:edit, :update]
不要なら削除で！

2023-11-24 14:10 UTC, yuki-b4 commented on app/controllers/recipes_controller.rb
> +      # redirect_to_recipes_path
不要なら削除で！

2023-11-24 14:10 UTC, yuki-b4 commented on app/controllers/recipes_controller.rb
> +    # merge(user_id: current_user.id,id: params[:recipe_id])
不要なら削除で！

2023-11-24 14:10 UTC, yuki-b4 commented on app/views/recipes/new.html.erb
> -<h1>レシピ新規作成</h1>
これレシピの新規作成画面の表示は「新規作成」のままになっていますか？なってないと思うので修正ください！

2023-11-24 17:32 UTC, 12a1070 commented on app/controllers/recipes_controller.rb
> +    # merge(user_id: current_user.id,id: params[:recipe_id])
コメントアウトのことでしょうか？

2023-11-24 22:57 UTC, yuki-b4 commented on app/controllers/recipes_controller.rb
> +    # merge(user_id: current_user.id,id: params[:recipe_id])
そうです！

2023-11-25 07:02 UTC, yuki-b4 requested changes

2023-11-25 07:02 UTC, yuki-b4 commented on app/views/recipes/index.html.erb
> +# ユーザーがログイン状態なら以下の処理をする。
コメントアウトが間違っている気がします！この文字列が画面上に表示されていないか確認ください。

2023-11-25 07:09 UTC, 12a1070 commented on app/views/recipes/index.html.erb
> +# ユーザーがログイン状態なら以下の処理をする。
<img width="702" alt="スクリーンショット 2023-11-25 16 04 36" src="https://github.com/12a1070/Your-Recipes/assets/86764150/67dd3934-4b77-4acd-babf-a386982c7324">

--コメントアウトが間違っている
これでしょうか？コメント削除ということでしょうか？

2023-11-25 13:23 UTC, yuki-b4 approved these changes

2023-11-25 14:59 UTC, merged