Destroy
12a1070/Your-Recipes pull request #8
Opened 2023-12-01 06:47 UTC by 12a1070

レシピ削除機能
-削除リンク作成
-ユーザーがログイン状態で<% if user_signed_in? %>
レシピを投稿した投稿したユーザーと同じユーザーIDなら<% if recipe.user_id == current_user.id %>
<%= link_to recipe_path(@resipe.id), method: :delete, data: {confirm: "削除しますか？"} %>

パスできず・・・

2023-12-03 23:21 UTC, 12a1070 commented
レシピ削除機能（5h）
-ユーザーがログイン状態で<% if user_signed_in? %>
レシピを投稿した投稿したユーザーと同じユーザーIDなら<% if recipe.user_id == current_user.id %>
<%= link_to recipe_path(@resipe.id), method: :delete, data: {confirm: "削除しますか？"} %>

recipeモデルのbelongs_to :user,dependent: :destroyをbelongs_to :userにしたら削除できた。

2023-12-04 13:34 UTC, yuki-b4 requested changes
@12a1070 
お願いします！

2023-12-04 13:34 UTC, yuki-b4 commented on app/views/layouts/application.html.erb
> +          </ul>
ulの使い方が間違っています。
以下の使い方が正しい使い方です。必要がなければdivタグに変更しましょう。
```
<ul>
  <li>list1</li>
  <li>list2</li>
</ul>
```

2023-12-04 14:22 UTC, 12a1070 reviewed
```
 <div><% if @recipe.photo_url.present? %></div>
  <div><%= image_tag @recipe.photo_url %></div>
<div>必要な具材</div>
<div><%= @recipe.material %></div>
<div>料理手順</div>
<div><%= @recipe.process %></dive>
<div><% if user_signed_in? %></div>
<div>  <% if @recipe.user_id == current_user.id %></div>
   <div> <%= link_to 'レシピを削除する',recipe_path(@recipe.id), data: { turbo_method: :delete, turbo_confirm: " 本当に削除しますか?" } %></div>
```
[https://qiita.com/oudon722/items/67531d97743c71dc143d](url)
のように各要素全てにdivタグをつける形でいいでしょうか？

2023-12-04 14:22 UTC, 12a1070 commented on app/views/layouts/application.html.erb
> +          </ul>
[https://azuuun-memorandum.hatenablog.com/entry/2016/05/20/011718](url)
[https://pikawaka.com/rails/link_to](url)
divタグを使う場合をクラスを当てるつ用があるので
```
<ul>
  <li>list1</li>
  <li>list2</li>
</ul>
```
を使います。

2023-12-05 12:43 UTC, yuki-b4 commented
今必要ないなら付けなくても良いです！あくまでpタグである必要性を感じなかったので指摘しました！

2023-12-06 01:29 UTC, merged